export const dummyTickets = [
    {
        id: 1,
        busName: "Bintang Utara",
        origin: "makassar",
        destination: "toraja",
        departureTime: "08:00",
        arrivalTime: "14:30",
        price: 120000,
        date: "2025-04-05",
        seatAvailable: 12,
        order_online: false,
    },
    {
        id: 2,
        busName: "Toraja Express",
        origin: "makassar",
        destination: "toraja",
        departureTime: "10:00",
        arrivalTime: "16:30",
        price: 135000,
        date: "2025-04-05",
        seatAvailable: 7,
        order_online: false,
    },
    {
        id: 3,
        busName: "Sulsel Trans",
        origin: "makassar",
        destination: "toraja",
        departureTime: "09:00",
        arrivalTime: "15:00",
        price: 150000,
        date: "2025-04-05",
        seatAvailable: 4,
        order_online: true,
    },
    {
        id: 3,
        busName: "Manggala Trans",
        origin: "makassar",
        destination: "toraja",
        departureTime: "09:00",
        arrivalTime: "15:00",
        price: 150000,
        date: "2025-04-06",
        seatAvailable: 4,
        order_online: false,
    },
]
